project:
  type: website
  output-dir: docs

website:
  title: "Data Donation Studies: COMPTEXT Workshop"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: github
        href: https://github.com/valeriehase/comptext-data-donation
      - icon: website
        href: https://data-donation-science.de

format:
  html:
    theme: lux
    toc: true

